# 开发环境配置
# 敏感信息请在 application-secret.properties 中配置

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learnsphere_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
  # 热更新配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true

logging:
  level:
    com.learnsphere: debug
